name: PHP (Nette Tester)

on: [push, pull_request]

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: recursive
      - uses: shivammathur/setup-php@v2
        name: Setup PHP
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, mysql, soap, xml
          tools: composer
          ini-values: session.gc_probability=0, date.timezone="Europe/Prague", display_startup_errors = Off
      - name: Composer install
        run: composer install --no-progress --prefer-dist
      - run: composer run-script testCoverage
        name: Test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.html
      - if: failure()
        name: Failure output
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: tests/**/*.actual
